### ISSUE TITLE
A Simple Hello World App ?

### ISSUE THREAD

**Issue by stephane-lb** [goldsam/ng-golden-layout#1]
Hi,

Thanks for your amazing work, would that be possible to get a sample Hello world of an app using this package please ?

Cheers,

stephane-lb

**Comment by goldsam** [comment]
Sure. I will try to put something together that mimics one of the simple demos from the original golden-layout site.

**Comment by stephane-lb** [comment]
Hi,

Sorry to poke you again, did you have time to set something up? 

Cheers,

stephane-lb

**Comment by goldsam** [comment]
I didn't have as much time as I thought I would last weekend. I plan to get something up in the next day or two. Sorry for the late response.

**Comment by seekheart** [comment]
any examples?

**Comment by Arnie38** [comment]
He now has a reasonable hello world sample in \demos src directory.
I clone/built and was able to use the sample to create my own GL Angular based application.

**Comment by stephane-lb** [comment]
@Arnie38 Thanks, I will close it. Any link to your project ?

**Comment by Arnie38** [comment]
No public link; working on a commercial product but his demo was sufficient to get us started.
